src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C501_Class_Site_Mobile_Number__c</fullName>
        <label>Class Site Mobile Number</label>
        <type>Phone</type>
    </fields>
</CustomObject>

src/objects/Class_Site_Login_Attempt__c.object
<CustomObject>
    <description>Created by 501 Commons in 2019. 

Tracks logins to the Class Registration Site.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the account that attempted to log in.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Class Site Login Attempts</relationshipLabel>
        <relationshipName>Class_Site_Login_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Login_Attempts__c</fullName>
        <label>Login Attempts</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SMS_Timestamp__c</fullName>
        <label>SMS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Secret_Code__c</fullName>
        <label>Secret Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Class Site Login Attempt</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Site Login Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Site Login Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TwilioConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Twilio App Config</description>
    <fields>
        <fullName>AccountSid__c</fullName>
        <label>AccountSid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Send_Number__c</fullName>
        <label>Default Send Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Twilio Config</label>
</CustomObject>

src/classes/C501_TESTClassReg_Login.cls
@isTest
public class C501_TESTClassReg_Login {
    @testSetup static void setupAccount(){
        
        ID HHacctID	= [select id from Recordtype where Name='Household Account'].Id;

        Account testFamily = new Account(
            Name 								= 'Happy Household',
            C501_Class_Site_Mobile_Number__c 	= '2062222222',
            RecordTypeId						= HHacctID
        );
        insert testFamily;
        
        insert new TwilioConfig__c(Name = 'default', AuthToken__c = 'xxx', Default_Send_Number__c = '206222222', AccountSid__c = 'xxx');
        
    }
    
    @isTest static void testSimpleSuccessfulLoginDontRemember(){
        PageReference loginPage = Page.C501_ClassReg_Login;
        Test.setCurrentPage(loginPage);
        C501_CTRL_ClassReg_Login controller = new C501_CTRL_ClassReg_Login();
        System.assert( controller.pageStatus == 'start' );
        
        controller.phoneNumber = '(206) 222-2222';
        
        controller.lookupAccount();
        
        System.assert( controller.pageStatus == 'confirm' );
        
        List<Class_Site_Login_Attempt__c> attList = [
            SELECT 	id,
            		Account__c,
            		Secret_Code__c,
            		SMS_Timestamp__c,
            		Login_Attempts__c
            FROM	Class_Site_Login_Attempt__c
            ORDER BY SMS_Timestamp__c DESC
            LIMIT 	1
        ];
        
        controller.confirmation = attList[0].Secret_Code__c;
        controller.remember     = false;
        
        controller.confirmLogin();
    }
    
    @isTest static void testSimpleSuccessfulLogin(){
        PageReference loginPage = Page.C501_ClassReg_Login;
        Test.setCurrentPage(loginPage);
        C501_CTRL_ClassReg_Login controller = new C501_CTRL_ClassReg_Login();
        System.assert( controller.pageStatus == 'start' );
        
        controller.phoneNumber = '(206) 222-2222';
        
        controller.lookupAccount();
        
        System.assert( controller.pageStatus == 'confirm' );
        
        List<Class_Site_Login_Attempt__c> attList = [
            SELECT 	id,
            		Account__c,
            		Secret_Code__c,
            		SMS_Timestamp__c,
            		Login_Attempts__c
            FROM	Class_Site_Login_Attempt__c
            ORDER BY SMS_Timestamp__c DESC
            LIMIT 	1
        ];
        
        controller.confirmation = attList[0].Secret_Code__c;
        
        controller.confirmLogin();
    }

	@isTest static void testSimpleSuccessfulLookupConfirmFail(){
        PageReference loginPage = Page.C501_ClassReg_Login;
        Test.setCurrentPage(loginPage);
        C501_CTRL_ClassReg_Login controller = new C501_CTRL_ClassReg_Login();
        System.assert( controller.pageStatus == 'start' );
        
        controller.phoneNumber = '(206) 222-2222';
        
        controller.lookupAccount();
        
        System.assert( controller.pageStatus == 'confirm' );
        
        List<Class_Site_Login_Attempt__c> attList = [
            SELECT 	id,
            		Account__c,
            		Secret_Code__c,
            		SMS_Timestamp__c,
            		Login_Attempts__c
            FROM	Class_Site_Login_Attempt__c
            ORDER BY SMS_Timestamp__c DESC
            LIMIT 	1
        ];
        
        controller.confirmation = '1111111111';
        
        controller.confirmLogin();
        
        System.assert( controller.pageStatus == 'confirm-fail' );
        
    }

    @isTest static void testSimpleSuccessfulLookupConfirmFailBecauseNoReturnedList(){
        PageReference loginPage = Page.C501_ClassReg_Login;
        Test.setCurrentPage(loginPage);
        C501_CTRL_ClassReg_Login controller = new C501_CTRL_ClassReg_Login();
        System.assert( controller.pageStatus == 'start' );
        
        controller.phoneNumber = '(206) 222-2222';
        
        controller.lookupAccount();
        
        System.assert( controller.pageStatus == 'confirm' );
        
        List<Class_Site_Login_Attempt__c> attList = [
            SELECT 	id,
            		Account__c,
            		Secret_Code__c,
            		SMS_Timestamp__c,
            		Login_Attempts__c
            FROM	Class_Site_Login_Attempt__c
            ORDER BY SMS_Timestamp__c DESC
            LIMIT 	1
        ];
        
        String code = attList[0].Secret_Code__c;
        
        delete attList;
            
        controller.confirmation = code;
        
        controller.confirmLogin();
        
        System.assert( controller.pageStatus == 'confirm-fail' );
        
    }
    
    @isTest static void testSimpleLookupFail(){
        PageReference loginPage = Page.C501_ClassReg_Login;
        Test.setCurrentPage(loginPage);
        C501_CTRL_ClassReg_Login controller = new C501_CTRL_ClassReg_Login();
        System.assert( controller.pageStatus == 'start' );
        
        controller.phoneNumber = '(206) 222-0000';
        
        controller.lookupAccount();
        
        System.assert( controller.pageStatus == 'lookup-fail' );
        
    }

}