src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>East Bay</fullName>
                </value>
                <value>
                    <fullName>South Bay</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Class_Site_Login_Attempt__c.object
<CustomObject>
    <description>Created by 501 Commons in 2019. 

Tracks logins to the Class Registration Site.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the account that attempted to log in.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Class Site Login Attempts</relationshipLabel>
        <relationshipName>Class_Site_Login_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_Sent_To__c</fullName>
        <inlineHelpText>The Phone Number or Email Address the confirmation code was sent to.</inlineHelpText>
        <label>Code Sent To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Attempts__c</fullName>
        <label>Login Attempts</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SMS_Timestamp__c</fullName>
        <label>SMS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Secret_Code__c</fullName>
        <label>Secret Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Class Site Login Attempt</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Site Login Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Site Login Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Alternate_Contact_Phone__c</fullName>
        <inlineHelpText>Emergency Contact&apos;s Phone</inlineHelpText>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Authorized_Pickup_1_Name__c</fullName>
        <inlineHelpText>Authorized Pickup 1 Name</inlineHelpText>
        <label>Authorized Pickup 1 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Pickup_1_Phone__c</fullName>
        <inlineHelpText>Authorized Pickup 1&apos;s Phone #</inlineHelpText>
        <label>Authorized Pickup 1 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Authorized_Pickup_1_Relationship__c</fullName>
        <inlineHelpText>Authorized Pickup 1&apos;s Relationship to Child</inlineHelpText>
        <label>Authorized Pickup 1 Relationship</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Pickup_2_Phone__c</fullName>
        <inlineHelpText>Authorized Pickup 2&apos;s Phone #</inlineHelpText>
        <label>Authorized Pickup 2 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Authorized_Pickup_3_Phone__c</fullName>
        <inlineHelpText>Authorized Pickup 3&apos;s Phone #</inlineHelpText>
        <label>Authorized Pickup 3 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_2_Phone__c</fullName>
        <inlineHelpText>Emergency Contact 2&apos;s Phone</inlineHelpText>
        <label>Emergency Contact 2 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <inlineHelpText>Please select any terms that apply to your family.</inlineHelpText>
        <label>Family Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Refugee</fullName>
                </value>
                <value>
                    <fullName>Immigrant</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                </value>
                <value>
                    <fullName>Does not apply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Transportation__c</fullName>
        <inlineHelpText>Please choose one option regarding your child’s transportation home after Techbridge Girls program ends:</inlineHelpText>
        <label>Student Transportation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>May walk/bus home</fullName>
                </value>
                <value>
                    <fullName>Will receive a ride</fullName>
                    <label>Someone will pick up my child</label>
                </value>
                <value>
                    <fullName>My child can go to the after school program at the school</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/RegistrationSiteSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_From_Email__c</fullName>
        <inlineHelpText>Emails from the registration site will come from this email address</inlineHelpText>
        <label>Default From Email</label>
        <type>Email</type>
    </fields>
    <label>RegistrationSiteSettings</label>
</CustomObject>

src/objects/School_Term__c.object
<CustomObject>
    <description>Annual record of student&apos;s involvement in a techbridge program.</description>
    <fields>
        <fullName>Authorization_to_treat_minor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authorization to treat minor?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Contact for tracking parents</description>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <infoMessage>Choose a contact of record type Parent</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>School Terms (as Parent)</relationshipLabel>
        <relationshipName>School_Terms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Master-Detail to Account to track the school</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School Terms at School</relationshipLabel>
        <relationshipName>School_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_School_ID__c</fullName>
        <label>Student School ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Master Detail to Contact for student</description>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student, Alumna</value>
            </filterItems>
            <infoMessage>Find contact of record type Student</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>School Terms (as Student)</relationshipLabel>
        <relationshipName>School_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Waiver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver?</label>
        <type>Checkbox</type>
    </fields>
    <label>School Term</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>School Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>School Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TwilioConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Twilio App Config</description>
    <fields>
        <fullName>AccountSid__c</fullName>
        <label>AccountSid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Send_Number__c</fullName>
        <label>Default Send Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Twilio Config</label>
</CustomObject>

src/classes/C501_TEST_ClassReg_CreateAcct.cls
@isTest
public class C501_TEST_ClassReg_CreateAcct {
    
    // This is a temporary stand-in test for C501_CTRL_ClassReg_Home, which in current version has no use but which will become the main family management page. 
    @isTest static void tempTestHome(){
        C501_CTRL_ClassReg_Home controller = new C501_CTRL_ClassReg_Home();
    }
    
	@isTest static void testSuccessfulLogin(){
        Class_Site_Login_Attempt__c att = createLoggedInTestUser();
        
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        System.currentPageReference().getParameters().put('a', att.id);
        System.currentPageReference().getParameters().put('r', '1');
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'new');
        
    }
    
    @isTest static void testSuccessfulExistingCookie(){
        Class_Site_Login_Attempt__c att = createLoggedInTestUser();
        Cookie aIdTest = new cookie('LoginIdClassRegSite', att.Id, null, -1, false);
        
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        ApexPages.currentPage().setCookies(new Cookie[] {aIdTest});
        
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'new');
    }
    
    @isTest static void testLoginFail(){
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'fail');
    }
    
    @isTest static void testSuccessfulGoBack(){
        Class_Site_Login_Attempt__c att = createLoggedInTestUser();
        
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        System.currentPageReference().getParameters().put('a', att.id);
        System.currentPageReference().getParameters().put('r', '1');
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'new');
        
        controller.goBack();
        
    }
    
    @isTest static void testValidationFail(){
        insert new TwilioConfig__c(Name = 'default', AuthToken__c = 'xxx', Default_Send_Number__c = '206222222', AccountSid__c = 'xxx');
        insert new RegistrationSiteSettings__c(Name = 'default', Default_From_Email__c = 'salesforce@techbridgegirls.org');
        
        Class_Site_Login_Attempt__c att = createLoggedInTestUser();
        
        Account	school = new Account(Name='TestSchool',Region__c = 'Seattle');
        insert school;
        
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        System.currentPageReference().getParameters().put('a', att.id);
        System.currentPageReference().getParameters().put('r', '1');
        System.currentPageReference().getParameters().put('c', 'test@test.com');
        
        Test.startTest();
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'new');
        
        //System.assert(controller.getRegions().size() == 5);
        
        controller.schoolRegion				= 'Seattle';
        controller.refreshSchools();
        
        controller.parent.FirstName			= 'Test';
        controller.parent.LastName			= 'LastName';
        controller.parent.MobilePhone		= '9000';
        controller.parent.Email				= 'test@example.com';
        controller.parent.HomePhone			= 'bar';
        controller.parent.OtherPhone		= 'foo';
        controller.family.BillingStreet		= '123 Main St';
        controller.family.BillingCity		= 'Seattle';
        controller.family.BillingState		= 'WA';
        controller.family.BillingPostalCode	= '98101';
        
        controller.child.FirstName	= 'Child';
        controller.child.LastName	= 'Name';
        controller.child.MobilePhone = '123';
        controller.grade 			= null;
        controller.schoolName		= null;
        controller.term.Waiver__c	= false;
        
        controller.term.Student_School_ID__c 					= null;
        controller.noAllergies									= false;
        controller.child.Student_Transportation__c 				= 'Will receive a ride';
        controller.child.Authorized_Pickup_1_Name__c 			= 'Test friend';
        controller.child.Authorized_Pickup_1_Phone__c 			= 'derp';
        controller.child.Authorized_Pickup_1_Relationship__c 	= null;
        controller.child.Authorized_Pickup_2_Phone__c 			= 'huh';
        controller.child.Authorized_Pickup_3_Phone__c 			= 'NCC-1701';
        controller.child.Alternate_Contact_Phone__c 			= 'AAAH';
        controller.child.Emergency_Contact_2_Phone__c 			= '9';
        
        controller.createAccount();
                
        Test.stopTest();
        
        
    }
    
    @isTest static void testSuccessfulInsert(){
        insert new TwilioConfig__c(Name = 'default', AuthToken__c = 'xxx', Default_Send_Number__c = '206222222', AccountSid__c = 'xxx');
        insert new RegistrationSiteSettings__c(Name = 'default', Default_From_Email__c = 'salesforce@techbridgegirls.org');
        
        Class_Site_Login_Attempt__c att = createLoggedInTestUser();
        
        Account	school = new Account(Name='TestSchool',Region__c = 'Seattle');
        insert school;
        
        PageReference createAcctPage = Page.C501_ClassReg_CreateAcct;
        Test.setCurrentPage(createAcctPage);
        System.currentPageReference().getParameters().put('a', att.id);
        System.currentPageReference().getParameters().put('r', '1');
        System.currentPageReference().getParameters().put('c', 'test@test.com');
        
        Test.startTest();
        C501_CTRL_ClassReg_CreateAcct controller = new C501_CTRL_ClassReg_CreateAcct();
        System.assert(controller.pageStatus == 'new');
        
        //System.assert(controller.getRegions().size() == 5);
        
        controller.schoolRegion				= 'Seattle';
        controller.refreshSchools();
        
        controller.parent.FirstName			= 'Test';
        controller.parent.LastName			= 'LastName';
        controller.parent.MobilePhone		= '(623) 456-7890';
        controller.parent.Email				= 'test@example.com';
        controller.parent.HomePhone			= '(222) 287-1824';
        controller.parent.OtherPhone		= '(222) 287-1824';
        controller.family.BillingStreet		= '123 Main St';
        controller.family.BillingCity		= 'Seattle';
        controller.family.BillingState		= 'WA';
        controller.family.BillingPostalCode	= '98101';
        
        controller.child.FirstName	= 'Child';
        controller.child.LastName	= 'Name';
        controller.child.MobilePhone = '(222) 628-1928';
        controller.grade 			= '10';
        controller.schoolName		= school.Id;
        controller.term.Waiver__c	= true;
        controller.term.Authorization_to_treat_minor__c	= true;
        
        controller.term.Student_School_ID__c 					= 'abc123';
        controller.noAllergies									= true;
        controller.noSpecialNeeds								= true;
        controller.noMedication									= true;
        controller.child.Student_Transportation__c 				= 'Will receive a ride';
        controller.child.Authorized_Pickup_1_Name__c 			= 'Test friend';
        controller.child.Authorized_Pickup_1_Phone__c 			= '(206) 234-5678';
        controller.child.Authorized_Pickup_1_Relationship__c 	= 'BFF';
        controller.child.Authorized_Pickup_2_Phone__c 			= '(206) 234-5678';
        controller.child.Authorized_Pickup_3_Phone__c 			= '(206) 234-5678';
        controller.child.Alternate_Contact_Phone__c 			= '(206) 234-5678';
        controller.child.Emergency_Contact_2_Phone__c 			= '(206) 234-5678';
        
        controller.siteMultiPicklistReturnValues.put('Race__c',new List<String>{'White'});
        controller.siteMultiPicklistReturnValues.put('Family_Status__c',new List<String>{'Immigrant'});
        controller.siteMultiPicklistReturnValues.put('Preferred_Method_of_Contact__c',new List<String>{'Email'});
        controller.siteMultiPicklistReturnValues.put('Volunteer__c',new List<String>{'Other'});
        
        controller.createAccount();
        
        List<SelectOption> testListResult = controller.schoolList;
        
        List<SelectOption> regionList = C501_CTRL_ClassReg_CreateAcct.getRegions();
        
        Test.stopTest();
        
        List<School_Term__c> lookupTest = [
            SELECT	id,
            		Parent__c,
            		Parent__r.FirstName,
            		Student__c,
            		School__c,
            		School__r.Name
            FROM	School_Term__c
        ];
        
        System.assert( lookupTest.size() == 1 );
        System.assert( lookupTest[0].Parent__r.FirstName == 'Test' );
        System.assert( lookupTest[0].School__r.Name == 'TestSchool' );
    }
    
    public static Class_Site_Login_Attempt__c createLoggedInTestUser(){
        Class_Site_Login_Attempt__c att	= new Class_Site_Login_Attempt__c(
            Account__c 			= null,
            Login_Attempts__c	= 0,
            Secret_Code__c		= C501_UTIL_ClassRegUtilities.generateRandomString(6,true,false,false),
            SMS_Timestamp__c	= datetime.now(),
            Code_Sent_To__c     = 'test@email.com'
        );
        insert att;
        return att;
    }
}