src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C501_Class_Site_Mobile_Number_Lookup__c</fullName>
        <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(C501_Class_Site_Mobile_Number__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
        <inlineHelpText>Used to look up accounts on the class registration site.</inlineHelpText>
        <label>Class Site Mobile Number Lookup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_Class_Site_Mobile_Number__c</fullName>
        <label>Class Site Mobile Number</label>
        <type>Phone</type>
    </fields>
</CustomObject>

src/objects/Class_Site_Login_Attempt__c.object
<CustomObject>
    <description>Created by 501 Commons in 2019. 

Tracks logins to the Class Registration Site.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the account that attempted to log in.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Class Site Login Attempts</relationshipLabel>
        <relationshipName>Class_Site_Login_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Login_Attempts__c</fullName>
        <label>Login Attempts</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SMS_Timestamp__c</fullName>
        <label>SMS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Secret_Code__c</fullName>
        <label>Secret Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Class Site Login Attempt</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Site Login Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Site Login Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/C501_CTRL_ClassReg_Login.cls
public class C501_CTRL_ClassReg_Login {
    
    public 	String 	pageStatus		{get;set;}
    public 	String 	phoneNumber		{get;set;}
    public 	String 	confirmation	{get;set;}
    private ID		acctID			= null;
    
    public C501_CTRL_ClassReg_Login(){
        pageStatus		= 'start';
        phoneNumber		= '';
        confirmation	= '';
    }
    
    public PageReference confirmLogin(){
        String 		cleanedConfirm 		= confirmation.replaceAll('[^0-9]', '');
        Datetime 	thirtyMinutesAgo	= Datetime.now().addMinutes(-30);
        List<Class_Site_Login_Attempt__c> attList = [
            SELECT 	id,
            		Account__c,
            		Secret_Code__c,
            		SMS_Timestamp__c,
            		Login_Attempts__c
            FROM	Class_Site_Login_Attempt__c
            WHERE	//Secret_Code__c = :cleanedConfirm	AND
             		Account__c = :acctID
             AND	SMS_Timestamp__c > :thirtyMinutesAgo
            ORDER BY SMS_Timestamp__c DESC
            LIMIT 	1
        ];
        if(attList.size() > 0 ){
            if(attList[0].Secret_Code__c == cleanedConfirm){
                // redirect to the account manager page
            	return C501_UTIL_ClassRegUtilities.generatePageLink('C501_ClassReg_Home','a,s',acctID+','+cleanedConfirm);
            } else {
                pageStatus	= 'confirm-fail';
            	return null;
            }
        } else {
            pageStatus	= 'confirm-fail';
            return null;
        }
    }
    
    public PageReference lookupAccount(){
        // clean the input
        String cleanedPhone = phoneNumber.replaceAll('[^0-9]', '');
        
        // look up the account
        List<Account> acctList = [
            SELECT	id,
            		C501_Class_Site_Mobile_Number__c,
            		C501_Class_Site_Mobile_Number_Lookup__c
            FROM	Account
            WHERE	RecordType.Name = 'Household Account'
             AND	C501_Class_Site_Mobile_Number_Lookup__c		= :cleanedPhone
             AND	C501_Class_Site_Mobile_Number__c 			!= null
        ];
        if(acctList.size() > 0 ){
            // set acctID
            acctID	= acctList[0].id;
            // send the sms
            C501_UTIL_ClassRegUtilities.sendSMS(acctID);
        	// present user with a code screen
        	pageStatus	= 'confirm';
        	return null;
        } else {
            // login failed
            pageStatus	= 'lookup-fail';
            return null;
        }
    }
}