src/objects/Class_Site_Login_Attempt__c.object
<CustomObject>
    <description>Created by 501 Commons in 2019. 

Tracks logins to the Class Registration Site.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the account that attempted to log in.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Class Site Login Attempts</relationshipLabel>
        <relationshipName>Class_Site_Login_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Login_Attempts__c</fullName>
        <label>Login Attempts</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SMS_Timestamp__c</fullName>
        <label>SMS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Secret_Code__c</fullName>
        <label>Secret Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Class Site Login Attempt</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Site Login Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Site Login Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/C501_CTRL_ClassReg_Home.cls
public class C501_CTRL_ClassReg_Home {
    public String	acctID {get; set;}
    
    public C501_CTRL_ClassReg_Home(){
        acctID	= null;
        
        Cookie aId = ApexPages.currentPage().getCookies().get('AccountIdClassRegSite');
        if (aId != null){
            acctID = 'cookie found';//aId.getValue(); 
        } else {
            String acctPa = ApexPages.currentPage().getParameters().get('a');
            String secret = ApexPages.currentPage().getParameters().get('s');
            String rember = ApexPages.currentPage().getParameters().get('r');
            if(acctPa != null && secret != null){
                Datetime 	thirtyMinutesAgo	= Datetime.now().addMinutes(-30);
                List<Class_Site_Login_Attempt__c> attList = [
                    SELECT 	id,
                            Account__c,
                            Secret_Code__c,
                            SMS_Timestamp__c,
                            Login_Attempts__c
                    FROM	Class_Site_Login_Attempt__c
                    WHERE	Account__c = :acctPa
                     AND	SMS_Timestamp__c > :thirtyMinutesAgo
                    ORDER BY SMS_Timestamp__c DESC
                    LIMIT 	1
                ];
                if(attList.size() > 0 ){
            		if(attList[0].Secret_Code__c == secret){
                        acctID = attList[0].Account__c;
                        Integer remberInt = 86400;
                        if(rember != null && rember == '1'){
                            remberInt = -1;
                        }
                        aId = new cookie('AccountIdClassRegSite', acctID, null, remberInt, false);
						ApexPages.currentPage().setCookies(new Cookie[] {aId});
                    } else {
                        acctID = 'fail to validate';
                    }
                } else {
                    acctID = 'didn\'t find';
                }
            } else {
                acctID = 'no provided variables';
            }
        }
    }
}